package Trains;

import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JTextField;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class AjouterTrain extends javax.swing.JFrame {
    private AdminPanel adminPanel;
    private Connection con;
private ResultSet resultSet;
private int nb=0;
   
    private int currentRecord;
    // ResultSet rs=null;
      Statement st=null;
    public AjouterTrain(ResultSet resultSet) {
        this.resultSet = resultSet;
    }

    public AjouterTrain(AdminPanel adminPanel) {
        initComponents();
        fetchNextIDAndLoadIntoTextBox(TrainNumber);
           TrainNumber.setEditable(false);
        // Set the background color to grey
        TrainNumber.setBackground(Color.LIGHT_GRAY);
    
        this.adminPanel = adminPanel;
         setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
         addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            int confirmed = JOptionPane.showConfirmDialog(null,
                    "Etes-vous sûr de vouloir fermer l'application ?",
                    "Confirmation", JOptionPane.YES_NO_OPTION);

            if (confirmed == JOptionPane.YES_OPTION) {
                // If user confirms, close the application
                dispose(); // This line is optional depending on your application's needs
                System.exit(0);
            } else {
                // If user clicks "No" or closes the dialog, do nothing
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        TrainNumber = new javax.swing.JTextField();
        TrainplacesNum1cls = new javax.swing.JTextField();
        TrainCapacity = new javax.swing.JTextField();
        TrainMarque = new javax.swing.JTextField();
        TrainSpeed = new javax.swing.JTextField();
        TrainType = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        TrainNumber.setBackground(new java.awt.Color(0, 102, 102));
        TrainNumber.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TrainNumber.setForeground(new java.awt.Color(255, 255, 255));
        TrainNumber.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        TrainNumber.setSelectionColor(new java.awt.Color(0, 102, 102));

        TrainplacesNum1cls.setBackground(new java.awt.Color(0, 102, 102));
        TrainplacesNum1cls.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TrainplacesNum1cls.setForeground(new java.awt.Color(255, 255, 255));
        TrainplacesNum1cls.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        TrainplacesNum1cls.setSelectionColor(new java.awt.Color(0, 102, 102));

        TrainCapacity.setBackground(new java.awt.Color(0, 102, 102));
        TrainCapacity.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TrainCapacity.setForeground(new java.awt.Color(255, 255, 255));
        TrainCapacity.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        TrainCapacity.setSelectionColor(new java.awt.Color(0, 102, 102));

        TrainMarque.setBackground(new java.awt.Color(0, 102, 102));
        TrainMarque.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TrainMarque.setForeground(new java.awt.Color(255, 255, 255));
        TrainMarque.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        TrainMarque.setSelectionColor(new java.awt.Color(0, 102, 102));

        TrainSpeed.setBackground(new java.awt.Color(0, 102, 102));
        TrainSpeed.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TrainSpeed.setForeground(new java.awt.Color(255, 255, 255));
        TrainSpeed.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        TrainSpeed.setSelectionColor(new java.awt.Color(0, 102, 102));
        TrainSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainSpeedActionPerformed(evt);
            }
        });

        TrainType.setBackground(new java.awt.Color(0, 102, 102));
        TrainType.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TrainType.setForeground(new java.awt.Color(255, 255, 255));
        TrainType.setSelectedTextColor(new java.awt.Color(0, 102, 102));
        TrainType.setSelectionColor(new java.awt.Color(0, 102, 102));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Effacer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Router");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Train");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(TrainType, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(TrainCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(TrainplacesNum1cls, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(TrainSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TrainNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(TrainMarque)))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(TrainNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(TrainMarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TrainType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(TrainCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(TrainplacesNum1cls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TrainSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 0, 380, 675));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Type de Train");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numéro de Train.");

        jLabel35.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("1er class N° de Places");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("2eme class N° de Places");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vitesse du Train");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Marque de Train");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ajouter ");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(57, 57, 57)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(188, 188, 188)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 675));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TrainSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainSpeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrainSpeedActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TrainNumber.setText("");
        TrainType.setText("");
        TrainCapacity.setText("");
  
        TrainSpeed.setText("");
        TrainNumber.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
 public void fetchNextIDAndLoadIntoTextBox(JTextField id) {
        Connection connection = ConnectioDB.getConnection();
        String sql = "SELECT MAX(TrainNumber) AS max_id FROM Trains";

        try (
               PreparedStatement ps = connection.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {

            if (rs.next()) {
                int maxId = rs.getInt("max_id");
                int nextId = maxId + 1;
                TrainNumber.setText(Integer.toString(nextId));
            } else {
                // Handle the case where no result is returned
                TrainNumber.setText(""); // Clear the text box
            }

        } catch (SQLException ex) {
            // Handle SQL exception
            ex.printStackTrace();
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TrainBeans b = new TrainBeans();

        try {
            b.setTrainNumber(Integer.parseInt(TrainNumber.getText()));
        } catch (NumberFormatException e) {
            // Display a message in French for the specific textbox
            JOptionPane.showMessageDialog(null, "Le champ Numéro de Train doit être soit vide, soit un nombre entier.", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if the input is invalid
        }

    b.setTrainMarque(TrainMarque.getText().toLowerCase());
        b.setTrainType(TrainType.getText());

        try {
            b.setTrainCapacity(Integer.parseInt(TrainCapacity.getText()));
        } catch (NumberFormatException e) {
            // Display a message in French for the specific textbox
            JOptionPane.showMessageDialog(null, "Le champ de N° de Places en 2eme class doit etre soit vide, soit un nomber entier  .", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if the input is invalid
        }

        try {
            b.setTrainplacesNum1cls(Integer.parseInt(TrainplacesNum1cls.getText()));
        } catch (NumberFormatException e) {
            // Display a message in French for the specific textbox
            JOptionPane.showMessageDialog(null, "Le champ de N° de Places en 1ère classe doit être soit vide, soit un nombre entier.", "Erreur de saisie", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if the input is invalid
        }

      
        b.setTrainSpeed(TrainSpeed.getText());

        GareDB d = GareDB.getCon();
        d.AddTrain(b);
        fetchNextIDAndLoadIntoTextBox(TrainNumber);
 resetInputFields();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
   private void resetInputFields() {
        TrainNumber.setText("");
        TrainMarque.setText("");
        TrainType.setText("");
        TrainCapacity.setText("");
        TrainplacesNum1cls.setText("");
        
        TrainSpeed.setText("");
        TrainNumber.requestFocus();
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
showAdminPanel();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
 public void showAdminPanel() {
        if (adminPanel != null) {
            adminPanel.setVisible(true);
            this.setVisible(false);
        } else {
            System.out.println("AdminPanel is null. Make sure to initialize it before using.");
        }
    }
    /**
     * @param args the command line arguments
     */

 public static void main(String args[]) {
    final AdminPanel adminPanel = new AdminPanel();

    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            AjouterTrain ajouterTrainFrame = new AjouterTrain(adminPanel);
            ajouterTrainFrame.setVisible(true);
            adminPanel.setVisible(false);
        }
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TrainCapacity;
    private javax.swing.JTextField TrainMarque;
    private javax.swing.JTextField TrainNumber;
    private javax.swing.JTextField TrainSpeed;
    private javax.swing.JTextField TrainType;
    private javax.swing.JTextField TrainplacesNum1cls;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
